apiVersion: apps/v1
kind: Deployment
metadata: 
  name: myapp-deployment
  labels:
    tire: frontend
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 1
  template:
    metadata:
      name: myapp
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: anirudhabidave/kube-assignment